# ai generated cuz im too stupid to learn yaml lol :3
name: Build ARMv5 C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi qemu-user-static debootstrap

      - name: Set Up Sysroot
        run: |
          sudo debootstrap --arch=armel --foreign bullseye /path/to/sysroot http://deb.debian.org/debian/
          sudo cp /usr/bin/qemu-arm-static /path/to/sysroot/usr/bin/
          sudo chroot /path/to/sysroot /debootstrap/debootstrap --second-stage
          sudo chroot /path/to/sysroot apt-get install -y libx11-dev

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/sysroot/toolchain-armv5.cmake ..
          make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: armv5-build
          path: build/