# ai generated cuz im too stupid to learn yaml lol :3
name: Build ARMv5 C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ARMv5 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y clang gcc-arm-linux-gnueabi g++-arm-linux-gnueabi cmake libx11-dev libx11-xcb-dev libxrandr-dev libxext-dev libxi-dev

      - name: Set up CMake Toolchain File for ARMv5
        run: |
          mkdir -p $HOME/armv5-toolchain
          cat > $HOME/armv5-toolchain/toolchain-armv5.cmake <<EOF
          # toolchain-armv5.cmake
          SET(CMAKE_SYSTEM_NAME Linux)
          SET(CMAKE_SYSTEM_PROCESSOR arm)

          SET(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabi-gcc)
          SET(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabi-g++)

          SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv5te -mfloat-abi=soft -mfpu=vfp")
          EOF

      - name: Configure CMake for ARMv5
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$HOME/armv5-toolchain/toolchain-armv5.cmake

      - name: Build with CMake
        run: |
          cd build
          make VERBOSE=1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: armv5-build
          path: build/